# arch.yml --- Clang for Arch Linux
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Install clang using pacman
  pacman:
    name: clang
  become: yes
- name: Create a symlink for Clang Format config
  file:
    force: yes
    path: ~/.clang-format
    src: '{{ dotfiles_path }}/clang/clang-format'
    state: link
