# main.yml --- Clang
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a symlink for Clang Format config
  file:
    force: yes
    path: ~/.clang-format
    src: '{{ dotfiles_path }}/clang/clang-format'
    state: link
