#
# author: Seong Yong-ju ( @sei40kr )
---
- include_vars: "debian.yml"

- name: Install apt packages
  apt: { cache_valid_time: 3600, name: "{{ item }}", update_cache: true }
  with_items: "{{ virt_apt_pkgs }}"
  become: true
  tags: virt-app

