[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_sign_added = '┃'
let g:gitgutter_sign_modified = '┃'
let g:gitgutter_sign_modified_removed = '┃'
let g:gitgutter_sign_removed = '▸'
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['onedark.vim', 'vim-gitbranch', 'ale']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'source ~/.vim/rc/plugins/onedark.rc.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:indent_guides_default_mapping = 0

augroup indent_guides_hooks
  autocmd!
  autocmd VimEnter,ColorScheme onedark
      \ highlight link IndentGuidesOdd NONE
      \ | highlight IndentGuidesEven guibg=#2c323c ctermbg=236
augroup END
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['crystal', 'javascript']

let g:crystal_define_mappings = 0
'''

[[plugins]]
repo = 'shougo/dein.vim'

[[plugins]]
repo = 'shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = '''
function! g:Multiple_cursors_before()
  let g:deoplete#disable_auto_complete = 1
endfunction

function! g:Multiple_cursors_after()
  let g:deoplete#disable_auto_complete = 0
endfunction
'''

[[plugins]]
repo = 'thinca/vim-template'
hook_add = 'source ~/.vim/rc/plugins/vim-template.rc.vim'

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'
if = '!empty($TMUX)'
hook_add = '''
set autoread

augroup user_tmux_hooks
  autocmd!
  autocmd FocusGained * set cursorline
  autocmd FocusLost * set nocursorline
augroup END
'''

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/rc/plugins/ale.rc.vim'

