[[plugins]]
repo = 'chiel92/vim-autoformat'
on_cmd = 'Autoformat'
hook_add = 'source ~/.vim/rc/plugins/vim-autoformat.rc.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>(easymotion-'}
hook_add = '''
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
let g:EasyMotion_use_smartsign_jp = 1

nmap <Leader><Leader> <Plug>(easymotion-s)
'''

[[plugins]]
repo = 'edkolev/tmuxline.vim'
on_cmd = ['Tmuxline', 'TmuxlineSnapshot']
hook_add = '''
let g:tmuxline_preset = {
    \ 'win': '#I #W',
    \ 'cwin': '#I #W',
    \ 'z': '%R',
    \ 'options': {'status-justify': 'centre'}
    \ }
let g:tmuxline_separators = {
    \ 'left': '',
    \ 'left_alt': '|',
    \ 'right': '',
    \ 'right_alt': '|',
    \ 'space': ' '
    \ }
let g:tmuxline_theme = {
    \   'a': [145, 235],
    \   'b': [145, 235],
    \   'c': [145, 235],
    \   'x': [145, 235],
    \   'y': [145, 235],
    \   'z': [145, 235],
    \   'win': [145, 235],
    \   'cwin': [235, 4],
    \   'bg': [145, 235],
    \ }
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = {nx = '<Plug>(EasyAlign)'}
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'junegunn/vim-xmark'
if = "has('macunix')"
on_cmd = 'Xmark'
hook_build = 'make'

[[plugins]]
repo = 'kana/vim-gf-user'
on_map = {nv = ['gf', 'gF', '<C-w>f', '<C-w><C-f>', '<C-w>F', '<C-w>gf', '<C-w>gF']}
hook_source = 'source ~/.vim/rc/plugins/vim-gf-user.rc.vim'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'
on_map = {o = ['ae', 'ie']}

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = 'Gist'
hook_add = '''
let g:gist_detect_filetype = 1
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {nx = '<Plug>(jplus)'}
hook_add = '''
nmap J <Plug>(jplus)
xmap J <Plug>(jplus)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = {nox = ['F', 'T', 'f', 't']}
hook_add = '''
let g:clever_f_across_no_line = 1
let g:clever_f_ignore_case = 1
let g:clever_f_show_prompt = 1
let g:clever_f_smart_case = 1
'''

[[plugins]]
repo = 'rizzatti/dash.vim'
if = "has('macunix')"
on_cmd = ['Dash', 'DashKeywords']
hook_add = '''
let g:dash_map = {
  \   'apex': ['apex'],
  \   'visualforce': ['vf', 'html'],
  \ }

augroup dash_hooks
  autocmd!
  autocmd FileType apex nnoremap <buffer> gK :<C-u>Dash<CR>
augroup END
'''

[[plugins]]
repo = 'shougo/denite.nvim'
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir']
hook_add = '''
nnoremap <silent> <Leader>f :<C-u>DeniteProjectDir
    \ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'` -buffer-name=file-rec<CR>
nnoremap <silent> <Leader>F :<C-u>DeniteProjectDir grep -buffer-name=grep<CR>
nnoremap <silent> <Leader>n :<C-u>DeniteProjectDir grep -buffer-name=grep -immediately -resume -select=+1<CR>
nnoremap <silent> <Leader>p :<C-u>DeniteProjectDir grep -buffer-name=grep -immediately -resume -select=-1<CR>
nnoremap <silent> <Leader>o :<C-u>Denite outline -buffer-name=outline<CR>
nnoremap <silent> <Leader>h :<C-u>Denite help -buffer-name=help<CR>
nnoremap <silent> / :<C-u>Denite line -buffer-name=search -auto-highlight<CR>
nnoremap <silent> * :<C-u>DeniteCursorWord line -auto-highlight -buffer-name=search -mode=normal<CR>
nnoremap <silent> # :<C-u>DeniteCursorWord line -auto-highlight -buffer-name=search -mode=normal<CR>
'''
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'

[[plugins]]
repo = 'shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = 'source ~/.vim/rc/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_add = '''
let g:echodoc#enable_at_startup = 1
'''

[[plugins]]
repo = 'shougo/neoinclude.vim'
depends = 'deoplete.nvim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'shougo/neopairs.vim'
depends = 'deoplete.nvim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'shougo/neosnippet'
depends = ['deoplete.nvim', 'neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = 'snippet'
on_cmd = ['NeoSnippetMakeCache', 'NeoSnippetEdit', 'NeoSnippetSource', 'NeoSnippetClearMarker']
hook_source = '''
let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#expand_word_boundary = 1
let g:neosnippet#snippets_directory = expand('~/.vim/snippets')

imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'shougo/neosnippet-snippets'

[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = {nx = ['+', '_'], v = 'v'}
hook_add = '''
vmap v <Plug>(expand_region_expand)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
nnoremap <silent> <Leader>r :<C-u>QuickRun -mode n<CR>
vnoremap <silent> <Leader>r :<C-u>QuickRun -mode v<CR>
'''
hook_source = 'source ~/.vim/rc/plugins/vim-quickrun.rc.vim'

[[plugins]]
repo = 'tpope/vim-commentary'
on_map = {n = ['gc', 'gcc'], o = 'gc', x = 'gc'}

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull', 'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog',
    'Gllog', 'Gedit', 'Gsplit', 'Gvsplit', 'Gtabedit', 'Gpedit', 'Gread', 'Gwrite', 'Gwq', 'Gdiff', 'Gsdiff', 'Gvdiff',
    'Gmove', 'Gdelete', 'Gremove', 'Gblame', 'Gbrowse']

[[plugins]]
repo = 'tpope/vim-repeat'
on_map = {n = ['.', 'u', 'U', '<C-r>']}

[[plugins]]
repo = 'tpope/vim-surround'
depends = 'vim-repeat'
on_map = {n = ['cS', 'cs', 'ds', 'yS', 'ySS', 'ySs', 'ys', 'yss'], x = ['S', 'gS']}

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['OpenBrowser', 'OpenBrowserSearch', 'OpenBrowserSmartSearch']

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'
on_cmd = ['OpenGithubFile', 'OpenGithubIssue', 'OpenGithubPullReq']

[[plugins]]
repo = 'vim-scripts/gtags.vim'
on_cmd = ['Gtags', 'GtagsCursor', 'Gozilla']

