# main.yml --- cmus
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a directory for cmus config
  file:
    path: ~/.config/cmus
    recurse: yes
    state: directory
- name: Create a symlink for cmus config
  file:
    follow: no
    force: yes
    path: ~/.config/cmus/rc
    src: '{{ dotfiles_path }}/cmus/rc'
    state: link
- name: Create a directory for executables
  file:
    path: ~/.local/bin
    recurse: yes
    state: directory
- name: Create a symlink for cplay executable
  file:
    follow: no
    force: yes
    path: ~/.local/bin/cplay
    src: '{{ dotfiles_path }}/bin/cplay'
    state: link
