# main.yml --- ripgrep
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a symlink for ripgrep config
  file:
    follow: no
    force: yes
    path: ~/.ripgreprc
    src: '{{ dotfiles_path }}/ripgrep/ripgreprc'
    state: link
