# main.yml
# author: Seong Yong-ju ( @sei40kr )
---
dotfiles:
  repo: "https://github.com/sei40kr/dotfiles.git"
  dest: "~/dotfiles"
  src:
    - "/.tmux.conf"
    - "/.zsh"
    - "/.zshrc"
    - "/.vim"
    - "/.config/nvim"
    - "/.gitconfig"
    - "/.tigrc"
    - "/.globalrc"
    - "/.ideavimrc"
    - "/.gemrc"

