name:                my-xmonad
version:             0.1.0.0
github:              "sei40kr/dotfiles"
license:             MIT
author:              "Seong Yong-ju"
maintainer:          "sei40kr@gmail.com"
copyright:           "2020 Seong Yong-ju"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: ""

dependencies:
- base >=4.7 && <5
- containers
- directory
- xmonad >=0.15 && <0.16
- xmonad-contrib >=0.15 && <0.16

library:
  source-dirs: src

executables:
  my-xmonad:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
