# main.yml --- Rust
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/rust.yml
    name: rust
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Install Rust
  command: 'rustup toolchain install {{ item }}'
  with_items: '{{ rust.rust_versions }}'
- name: Add a component rust-src for the installed versions of Rust
  command: 'rustup component add --toolchain={{ item }} rust-src'
  with_items: '{{ rust.rust_versions }}'
- name: Set the installed version of Rust as default
  command: 'rustup default {{ rust.rust_default_version }}'
