# arch.yml --- Docker for Arch Linux
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Install docker, docker-compose using pacman
  pacman:
    name: '{{ item }}'
  become: yes
  with_items:
    - docker
    - docker-compose
