# main.yml --- Docker
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Add current user into docker group
  user:
    append: yes
    groups: [docker]
    name: '{{ ansible_ssh_user }}'
  become: yes
- name: Enable docker service
  systemd:
    enabled: yes
    name: docker.service
    state: started
  become: yes
