[[plugins]]
hook_add = '''
let g:onedark_termcolors = 16
'''
hook_post_source = '''
if (has("autocmd") && !has("gui_running"))
  augroup colorset
    autocmd!
    let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white })
  augroup END
endif

syntax on
colorscheme onedark
'''
repo = 'joshdick/onedark.vim'
rev = 'c0f22072c8780494afce1bc0c5ea4de252c4516f'
