[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
set background=dark

if (has('autocmd') && !has('gui_running'))
  augroup colorset
    autocmd!
    let s:white = { 'gui': '#ABB2BF', 'cterm': '145', 'cterm16' : '7' }
    autocmd ColorScheme * call onedark#set_highlight('Normal', { 'fg': s:white })
  augroup END
endif

colorscheme onedark
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'onedark.vim'
hook_add = '''
if !exists('g:lightline')
  let g:lightline = {}
endif

let g:lightline.colorscheme = 'onedark'
'''

[[plugins]]
repo = 'lambdalisue/vim-manpager'
depends = 'lightline.vim'
lazy = 1
on_cmd = 'MANPAGER'
hook_add = '''
set noshowmode

let g:lightline.component_function = {
  \ 'mode': 'LightlineMode',
  \ 'readonly': 'LightlineReadonly',
  \ 'filename': 'LightlineFilename',
  \ }

function! LightlineMode()
  return &filetype ==# 'man' ? 'ManPager' : lightline#mode()
endfunction

function! LightlineReadonly()
  return &readonly && &filetype ==# 'man' ? '' : 'RO'
endfunction

function! LightlineFilename()
  let filename = expand('%:t')

  return filename !=# '' ? filename :
    \ &filetype ==# 'man' ? '-' : '[No Name]'
endfunction
'''