[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
set background=dark

autocmd VimEnter * nested colorscheme onedark
'''
hook_post_source = '''
if (has('autocmd') && !has('gui_running'))
  augroup colorset
    autocmd!
    let s:white = { 'gui': '#ABB2BF', 'cterm': '145', 'cterm16' : '7' }
    autocmd ColorScheme * call onedark#set_highlight('Normal', { 'fg': s:white })
  augroup END
endif
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'joshdick/onedark.vim'
hook_add ='''
let g:lightline = {
  \ 'colorscheme': 'onedark',
  \ }
'''

[[plugins]]
repo = 'lambdalisue/vim-manpager'
on_cmd = 'MANPAGER'
