# main.yml
# author: Seong Yong-ju ( @sei40kr )
---
- include: "{{ include_src }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
  loop_control:
    loop_var: include_src

