[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'autozimu/languageclient-neovim'
hook_add = '''
let s:go_bin_dir = $GO_PATH . '/bin'
let s:python_bin_dir = $PYENV_ROOT . '/shims'
let s:ruby_bin_dir = $RBENV_ROOT . '/shims'
let s:nvm_bin_dir = $NVM_DIR . '/current/bin'

let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
    \   'dockerfile': [s:nvm_bin_dir . '/node', s:nvm_bin_dir . '/docker-langserver', '--stdin'],
    \   'go': [s:go_bin_dir . '/go-langserver'],
    \   'javascript': [s:nvm_bin_dir . '/node', s:nvm_bin_dir . '/javascript-typescript-stdio', '--cluster', '1'],
    \   'python': [s:python_bin_dir . '/pyls'],
    \   'ruby': [s:ruby_bin_dir . '/language_server'],
    \ }
'''

[[plugins]]
repo = 'chaoren/vim-wordmotion'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
let g:EditorConfig_core_mode = 'python_external'
let g:EditorConfig_exclude_patterns = ['scp://.*', 'fugitive://.*', 'gist:.*']
'''

[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'onedark.vim'
hook_add = '''
let g:lightline = {
    \   'colorscheme': 'onedark'
    \ }
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
let g:onedark_terminal_italics = 1
let g:onedark_color_overrides = {
    \   'red': {'gui': '#E06C75', 'cterm': '1', 'cterm16': '1'},
    \   'green': {'gui': '#98C379', 'cterm': '2', 'cterm16': '2'},
    \   'yellow': {'gui': '#E5C07B', 'cterm': '3', 'cterm16': '3'},
    \   'blue': {'gui': '#61AFEF', 'cterm': '4', 'cterm16': '4'},
    \   'purple': {'gui': '#C678DD', 'cterm': '5', 'cterm16': '5'},
    \   'cyan': {'gui': '#56B6C2', 'cterm': '6', 'cterm16': '6'},
    \   'white': {'gui': '#ABB2BF', 'cterm': '7', 'cterm16': '7'},
    \   'black': {'gui': '#282C34', 'cterm': '0', 'cterm16': '0'},
    \ }

augroup onedark_hooks
  autocmd!
  autocmd ColorScheme onedark highlight LineNr ctermbg=none
      \ | highlight NonText ctermbg=none
      \ | highlight Normal ctermbg=none
      \ | highlight SignColumn ctermbg=none
      \ | highlight VertSplit ctermbg=none
augroup END
'''

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'shougo/dein.vim'

[[plugins]]
repo = 'shougo/neosnippet-snippets'

[[plugins]]
repo = 'shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = '''
function! g:Multiple_cursors_before()
  let g:deoplete#disable_auto_complete = 1
endfunction

function! g:Multiple_cursors_after()
  let g:deoplete#disable_auto_complete = 0
endfunction
'''

[[plugins]]
repo = 'thinca/vim-template'
hook_add = 'source ~/.vim/rc/plugins/vim-template.rc.vim'

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/rc/plugins/ale.rc.vim'

