# main.yml --- Redshift
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- include_tasks: linux.yml
  when: ansible_system == 'Linux'
