# config.yml
# author: Seong Yong-ju <sei40kr@gmail.com>
---
templates:
  content_size_anime_ep:
    content_size:
      min: 128
      max: 1024
      strict: yes
  transmission:
    transmission:
      host: 127.0.0.1
      port: 9091
  transmission_movies:
    transmission:
      # path: /Users/sei40kr/Movies
tasks:
  '<Name>':
    rss: '<RSS URL>'
    accept_all: yes
    template:
      # - content_size_anime_ep
      - transmission
      - transmission_movies
