# config.toml --- Go package list for gotcha
# author: Seong Yong-ju <sei40kr@gmail.com>
#
# gotcha is a simple tool that grabs Go packages
# cf https://github.com/b4b4r07/gotcha

repos = [
    'github.com/ForceCLI/force',
    'github.com/alecthomas/gometalinter',
    'github.com/golang/lint/golint',
    'github.com/heroku/force',
    'github.com/heppu/gkill',
    'github.com/jackc/sqlfmt',
    'github.com/nsf/gocode',
    'github.com/sourcegraph/go-langserver',
    'golang.org/x/tools/cmd/goimports',
    'gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira',
  ]
