# main.yml --- fish shell
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: '{{ item.file }}'
    name: '{{ item.name }}'
  with_items:
    - file: ../vars/main.yml
      name:
    - file: ../vars/fish.yml
      name: fish
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create directories for fish shell config
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  with_items:
    - ~/.config/fish/conf.d
    - ~/.config/fish/functions
- name: Create symlinks for fish shell config
  file:
    follow: no
    force: yes
    path: '{{ item.dest }}'
    src: '{{ item.src }}'
    state: link
  with_items:
    - src: '{{ dotfiles_path }}/fish/functions/fish_user_key_bindings.fish'
      dest: ~/.config/fish/functions/fish_user_key_bindings.fish
- name: Check if fisherman exists
  stat:
    path: ~/.config/fish/functions/fisher.fish
  register: fisher_check
- name: Install fisherman
  get_url:
    url: '{{ fish.fisherman_download_url }}'
    dest: ~/.config/fish/functions/fisher.fish
  when: not fisher_check.stat.exists
- name: Create a symlink for fisherman config
  file:
    follow: no
    force: yes
    path: ~/.config/fish/fishfile
    src: '{{ dotfiles_path }}/fish/fishfile'
    state: link
