# main.yml --- fish shell
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: '{{ item.file }}'
    name: '{{ item.name }}'
  with_items:
    - file: ../vars/main.yml
      name:
    - file: ../vars/fish.yml
      name: fish
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create directories for fish shell config
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  with_items:
    - ~/.config/fish/conf.d
    - ~/.config/fish/functions
- name: Create a symlink for fish shell config
  file:
    follow: no
    force: yes
    path: '{{ item.dest }}'
    src: '{{ item.src }}'
    state: link
  with_items:
    - src: '{{ dotfiles_path }}/fish/config.fish'
      dest: ~/.config/fish/config.fish
    - src: '{{ dotfiles_path }}/fish/conf.d/abbreviations.fish'
      dest: ~/.config/fish/conf.d/abbreviations.fish
    - src: '{{ dotfiles_path }}/fish/conf.d/tmux.fish'
      dest: ~/.config/fish/conf.d/tmux.fish
- name: Create symlinks for fish shell functions
  file:
    follow: no
    force: yes
    path: '~/.config/fish/functions/{{ item }}.fish'
    src: '{{ dotfiles_path }}/fish/functions/{{ item }}.fish'
    state: link
  with_items:
    - '{{ fish.fish_functions }}'
- name: Check if fisherman exists
  stat:
    path: ~/.config/fish/functions/fisher.fish
  register: fisher_check
- name: Install fisherman
  get_url:
    url: '{{ fish.fisherman_download_url }}'
    dest: ~/.config/fish/functions/fisher.fish
  when: not fisher_check.stat.exists
- name: Create symlinks for fisherman config
  file:
    follow: no
    force: yes
    path: ~/.config/fish/fishfile
    src: '{{ dotfiles_path }}/fish/fishfile'
    state: link
