# linux.yml --- GTK for Linux
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- name: Create directories for GTK config
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  with_items:
    - ~/.config/gtk-2.0
    - ~/.config/gtk-3.0
- name: Create symlinks for GTK config
  file:
    follow: no
    force: yes
    path: '{{ item.dest }}'
    src: '{{ item.src }}'
    state: link
  with_items:
    - src: '{{ dotfiles_path }}/gtk-2.0/gtkrc'
      dest: ~/.config/gtk-2.0/gtkrc
    - src: '{{ dotfiles_path }}/gtk-2.0/gtkfilechooser.ini'
      dest: ~/.config/gtk-2.0/gtkfilechooser.ini
    - src: '{{ dotfiles_path }}/gtk-3.0/settings.ini'
      dest: ~/.config/gtk-3.0/settings.ini
