# python.yml --- Python 2 & Python 3
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/python.yml
    name: python
- name: Check if pyenv exists
  stat:
    path: '{{ python.pyenv_root }}'
  register: pyenv_check
- name: Install pyenv
  git:
    dest: '{{ python.pyenv_root }}'
    repo: '{{ python.pyenv_repo }}'
  when: not pyenv_check.stat.exists
- name: Check if pyenv-ccache exists
  stat:
    path: '{{ python.pyenv_ccache_path }}'
  register: pyenv_ccache_check
- name: Install pyenv-ccache 
  git:
    dest: '{{ python.pyenv_ccache_path }}'
    repo: '{{ python.pyenv_ccache_repo }}'
  when: not pyenv_ccache_check.stat.exists
- name: Check if pyenv-virtualenv exists
  stat:
    path: '{{ python.pyenv_virtualenv_path }}'
  register: pyenv_virtualenv_check
- name: Install pyenv-virtualenv 
  git:
    dest: '{{ python.pyenv_virtualenv_path }}'
    repo: '{{ python.pyenv_virtualenv_repo }}'
  when: not pyenv_virtualenv_check.stat.exists
- name: Install Python 2
  shell: '{{ python.pyenv_root }}/bin/pyenv install -s {{ item }}'
  with_items: '{{ python.python2_versions }}'
- name: Install Python 2 packages
  pip:
    executable: '{{ python.pyenv_root }}/versions/{{ item }}/bin/pip2'
    name: '{{ python.pip2_packages }}'
  with_items:
    - '{{ python.python2_versions }}'
- name: Install Python 3
  shell: '{{ python.pyenv_root }}/bin/pyenv install -s {{ item }}'
  with_items: '{{ python.python3_versions }}'
- name: Install Python 3 packages
  pip:
    executable: '{{ python.pyenv_root }}/versions/{{ item }}/bin/pip3'
    name: '{{ python.pip3_packages }}'
  with_items:
    - '{{ python.python3_versions }}'
- name: Set the installed versions of Python as default
  shell: '{{ python.pyenv_root }}/bin/rbenv global {{ python.python3_default_version }} {{ python.python2_default_version }} && {{ python.pyenv_root }}/bin/rbenv rehash'
