# ruby.yml --- Ruby
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/ruby.yml
    name: ruby
- name: Install rbenv
  git:
    dest: '{{ ruby.rbenv_root }}'
    force: yes
    repo: '{{ ruby.rbenv_repo }}'
- name: Install ruby-build
  git:
    dest: '{{ ruby.ruby-build_path }}'
    force: yes
    repo: '{{ ruby.ruby-build_repo }}'
- name: Install Ruby
  shell: '{{ ruby.rbenv_root }}/bin/rbenv install -s {{ item }}'
  with_items: '{{ ruby.ruby_versions }}'
- name: Install Rubygems
  gem:
    executable: '{{ ruby.rbenv_root }}/versions/{{ item[0] }}/bin/gem'
    name: '{{ item[1] }}'
  with_nested:
    - '{{ ruby.ruby_versions }}'
    - '{{ ruby.rubygems }}'
- name: Set the installed version of Ruby as default
  shell: '{{ ruby.rbenv_root }}/bin/rbenv global {{ ruby.ruby_default_version }} && {{ ruby.rbenv_root }}/bin/rbenv rehash'
