# main.yml --- ZSH
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: '{{ item.file }}'
    name: '{{ item.name }}'
  with_items:
    - file: ../vars/main.yml
      name:
    - file: ../vars/zsh.yml
      name: zsh
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a symlink for ZSH config
  file:
    follow: no
    force: yes
    path: ~/.zsh
    src: '{{ dotfiles_path }}/zsh'
    state: link
- name: Create a directory for ZSH cache
  file:
    path: ~/.cache/zsh
    recurse: yes
    state: directory
- name: Check if zplugin exists
  stat:
    path: '{{ zsh.zplugin_path }}/bin'
  register: zplugin_check
# TODO Fix errors
- name: Create a directory for zplugin
  file:
    path: '{{ zsh.zplugin_path }}'
    recurse: yes
    state: directory
- name: Install zplugin
  git:
    dest: '{{ zsh.zplugin_path }}/bin'
    repo: '{{ zsh.zplugin_repo }}'
  when: not zplugin_check.stat.exists
- name: Locate the installed executable of zsh
  shell: 'which zsh'
  changed_when: False
  register: zsh_which
- name: Set zsh as the login shell
  user:
    name: '{{ ansible_ssh_user }}'
    shell: '{{ zsh_which.stdout_lines[0] }}'
  become: yes
