# main.yml --- ZSH
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: '{{ item.file }}'
    name: '{{ item.name }}'
  with_items:
    - file: ../vars/main.yml
      name:
    - file: ../vars/zsh.yml
      name: zsh
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a symlink for ZSH config
  file:
    follow: no
    force: yes
    path: ~/.zsh
    src: '{{ dotfiles_path }}/zsh'
    state: link
- name: Check if zplugin exists
  stat:
    path: '{{ zsh.zplugin_path }}/bin'
  register: zplugin_check
- name: Create a directory for zplugin
  file:
    path: ~/.zsh/.zplugin
    recurse: yes
    state: directory
- name: Install zplugin
  git:
    dest: '{{ zsh.zplugin_path }}/bin'
    repo: '{{ zsh.zplugin_repo }}'
  when: not zplugin_check.stat.exists
