# main.yml
# author: Seong Yong-ju ( @sei40kr )
---
- include: "{{ include_src }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
  loop_control:
    loop_var: include_src

- name: Setup user permissions
  user: { name: "{{ ansible_env.USER }}", groups: docker, append: true }
  become: true
  tags: os-app

- name: Locate zsh executable
  check_mode: false
  command: which zsh
  register: zsh_exec
  changed_when: false
  tags: os-app

- name: Setup zsh as default shell
  user: { name: "{{ ansible_env.USER }}", shell: "{{ zsh_exec.stdout | quote }}" }
  become: true
  tags: os-app

