# arch.yml --- Git for Arch Linux
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Install git using pacman
  pacman:
    name: '{{ item }}'
  become: yes
  with_items:
    - git
    - openssh
