# main.yml --- Git
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Include variables
  include_vars:
    file: ../vars/main.yml
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
- name: Create a symlink for Git config
  file:
    follow: no
    force: yes
    path: ~/.gitconfig
    src: '{{ dotfiles_path }}/git/gitconfig'
    state: link
- name: Generate a SSH key for current user
  user:
    generate_ssh_key: yes
    name: '{{ ansible_ssh_user }}'
    ssh_key_bits: 256
    ssh_key_type: ecdsa
