# arch.yml --- Xorg for Arch Linux
# author: Seong Yong-ju <sei40kr@gmail.com>
---
- name: Install xorg, xorg-xinit, xterm using pacman
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xterm
  become: yes
