[codestyle]
indent_type='space'
indent_width=4
template_file='~/my_template.rs'
workspace_dir='~/develop/workspace/sei40kr/hello-atcoder/'
lang='rust'
code_generator_file="~/custom_code_generator.py"

[postprocess]
exec_on_each_problem_dir='rustfmt -q main.rs; cargo init -q'
# exec_on_contest_dir='touch CMakeLists.txt'

[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
