# node.yml --- Node
# author: Seong Yong-ju <sei40kr@gmail.com>
---
nvm_repo: 'https://github.com/creationix/nvm.git'
nvm_dir: '~/.nvm'

node_versions:
  - v8.11.2
node_default_version: v8.11.2
node_npm_packages:
  - create-react-app
  - create-react-native-app
  - eslint-cli
  - eslint_d
  - flow-bin
  - gatsby-cli
  - generate
  - generate-gitignore
  - generate-license
  - generate-project
  - gulp
  - import-js
  - markdownlint-cli
  - prettier
  - prettier-eslint-cli
  - solc-js
  - stylelint-cli
  - typescript
  - typescript-language-server
  - vmd
  - webpack
  - yo
