# ruby.yml --- Ruby
# author: Seong Yong-ju <sei40kr@gmail.com>
---
rbenv_repo: 'https://github.com/rbenv/rbenv.git'
rbenv_root: '~/.rbenv'
rbenv-build_repo: 'https://github.com/rbenv/ruby-build.git'
rbenv-build_path: '~/.rbenv/plugins/ruby-build'

ruby_versions:
  - 2.5.0
ruby_default_version: 2.5.0

rubygems:
  - awesome_print
  - bundler
  - circle-cli
  - fastri
  - mdl
  - pry
  - pry-coolline
  - pry-doc
  - rake
  - rcodetools
  - rubocop
  - sublime2yas
  - travis
